# Generated by Django 3.0.8 on 2020-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='RexItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('R', 'Rexine'), ('D', 'Duroflex'), ('A', 'Adhesive'), ('NW', 'Nonwoven'), ('p', 'Powermax'), ('ER', 'Epe roll'), ('ES', 'Epe sheet')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('R', 'Rexine'), ('D', 'Duroflex'), ('A', 'Adhesive'), ('NW', 'Nonwoven'), ('p', 'Powermax'), ('ER', 'Epe roll'), ('ES', 'Epe sheet')], max_length=2),
        ),
    ]
