# Generated by Django 3.0.8 on 2020-08-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200804_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('R', 'Rexine'), ('PU', 'Pufoam'), ('A', 'Adhesive'), ('NW', 'Nonwoven'), ('P', 'Powermax'), ('LL', 'Epe roll'), ('ES', 'Epe sheet')], max_length=2),
        ),
    ]
