# Generated by Django 3.0.8 on 2020-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200808_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('R', 'Rexine'), ('PU', 'Pufoam'), ('A', 'Adhesive'), ('NW', 'Nonwoven'), ('PO', 'Powermax'), ('EL', 'Epe roll'), ('ES', 'Epe sheet')], max_length=2),
        ),
    ]
