# Generated by Django 3.0.8 on 2020-08-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200816_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Message',
        ),
    ]
