# Generated by Django 3.0.8 on 2020-08-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200817_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
